/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/bloodsport.glb 
Author: SketchSupreme (https://sketchfab.com/sketchsupreme)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bloodsport-fortnite-dc-collab-item-shop-skin-72f22690981a455fa6561b0b33267e21
Title: Bloodsport | Fortnite D.C Collab Item Shop Skin
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Bloodsport(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/bloodsport.glb')
  const { actions } = useAnimations(animations, group)

  console.log(actions)

  useEffect (()=>{
    actions["M_MED_Seesaw_Slipper.ao|ProgressiveJonesy_Male_Idle"].play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="1e332585851e41e18c76025f8a276f1efbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="M_MED_Seesaw_Slipperao" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5" scale={0.05} position={[-3.8,-15,-6.5]} rotation={[0,0,0.7]}>
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_141" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.M_MED_Seesaw_Slipper_Body} skeleton={nodes.Object_142.skeleton} />
                    <skinnedMesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.M_MED_Seesaw_Slipper_FaceAcc} skeleton={nodes.Object_143.skeleton} />
                  </group>
                </group>
                <group name="M_MED_Seesaw_Slippermo" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/bloodsport.glb')
