/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/snake.glb 
Author: SketchSupreme (https://sketchfab.com/sketchsupreme)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/snake-eyes-fortnite-item-shop-skin-eabab8d8df0046679ad70290d6f7e643
Title: Snake Eyes | Fortnite Item Shop Skin
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Snake (props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/snake.glb')
  const { actions } = useAnimations(animations, group)
  console.log(actions)
  useEffect (()=>{
    actions["M_MED_Convoy_Tarantula.ao|(ConvoyTarantula_Male_Idle) ConvoyTarantula_Male_Idle"].play();
  })
  return (
    <group ref={group} {...props} dispose={null} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="4496d9862bd54fa69dec3d6333791020fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="M_MED_Convoy_Tarantulaao" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5" scale={0.05} position={[3.8,-15,-5.6]} rotation={[0,0,5.2]}>
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_156" position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_159" position={[-1449.392, 12017.904, -1585.032]} rotation={[-1.418, 0.067, 1.044]} scale={100} />
                    <group name="Object_161" position={[2158.629, 9854.53, 1973.25]} rotation={[-2.286, -0.13, 3.066]} scale={100} />
                    <skinnedMesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials.M_MED_Convoy_Tarantula_Body} skeleton={nodes.Object_157.skeleton} />
                    <skinnedMesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.M_MED_Convoy_Tarantula_Head} skeleton={nodes.Object_158.skeleton} />
                    <skinnedMesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.M_MED_Convoy_Tarantula} skeleton={nodes.Object_160.skeleton} />
                    <skinnedMesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.MI_Pickaxe_Comet_Male} skeleton={nodes.Object_162.skeleton} />
                  </group>
                </group>
                <group name="M_MED_Convoy_Tarantulamo" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="M_MED_Convoy_Tarantula_Packmo" position={[-1449.392, 12017.904, -1585.032]} rotation={[-1.418, 0.067, 1.044]} scale={100} />
                <group name="Convoy_Tarantula_Malemo" position={[2158.629, 9854.529, 1973.25]} rotation={[-2.286, -0.13, 3.066]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/snake.glb')
